---

services:
  apache:
    enabled: false
    version: latest
    ram: 256M
    service_name: WebServer (Apache)
    service_url: http(s)://{}
  nginx:
    enabled: false
    version: latest
    ram: 256M
    document_root: /var/www
    service_name: WebServer (Nginx)
    service_url: http(s)://{}
  varnish:
    enabled: false
    version: latest
    ram: 256M
    service_name: Cache Server (Varnish)
    service_url: http(s)://{}
