version: '2.2'

services:
    apache:
        image: edyan/apache:${DOCKER_APACHE_VERSION}
        mem_limit: ${DOCKER_APACHE_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_apache
        hostname: ${COMPOSE_PROJECT_NAME}_apache
        networks: [stakkr]
        environment:
            APACHE_UID: ${DOCKER_UID}
            APACHE_GID: ${DOCKER_GID}
        volumes:
            - ${COMPOSE_BASE_DIR}/home/www-data:/home/www-data
            - ${COMPOSE_BASE_DIR}/logs/apache:/var/log/apache2
            - ${COMPOSE_BASE_DIR}/www:/var/www
        labels:
            - traefik.frontend.rule=Host:apache.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
