version: "3.8"

services:
  varnish:
    container_name: ${COMPOSE_PROJECT_NAME}_varnish
    image: varnish:${DOCKER_VARNISH_VERSION:-latest}
    hostname: ${COMPOSE_PROJECT_NAME}_varnish
    labels:
      traefik.enable: "true"
      traefik.http.services.varnish.loadbalancer.server.port: 80
      traefik.http.routers.varnish.tls: "true"
      traefik.http.routers.varnish.rule: "Host(`varnish.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
    mem_limit: ${DOCKER_VARNISH_RAM:-256M}
    networks: [stakkr]
    volumes:
      - ${COMPOSE_BASE_DIR}/conf/varnish/default.vcl:/etc/varnish/default.vcl:ro
